resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/rjain-pivotal/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/ci/tasks/build.yml
